# Local Development Only
# - ports are exposed to the host for debugging purposes
#
# Production
# - ensure only ports 80 and 443 are exposed to the host (nginx)
# - all other ports must not be accessible from the host

version: '3.9'
services:

  flask-server:
    # default port 5000
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api-flask-server
    depends_on:
      - database
      - nginx
    networks:
      - core-api
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./logs/metrics:/code/logs/metrics
      - ./migrations:/code/migrations
    restart: unless-stopped

  database:
    # default port 5432
    image: postgres:14
    container_name: api-database
    restart: unless-stopped
    networks:
      - core-api
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
#    volumes:
#      - ${PGDATA_LOCAL}:${PGDATA}

  nginx:
    # default port 8443, 80
    image: nginx:1
    container_name: api-nginx
    networks:
      - core-api
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl
    restart: unless-stopped

  vouch-proxy:
    # default port 9090
    container_name: api-vouch-proxy
    image: fabrictestbed/vouch-proxy:0.27.1
    networks:
      - core-api
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./vouch:/config
    restart: unless-stopped

networks:
  core-api:
    name: core-api
    driver: bridge