import logging
import os
from uuid import uuid4

from swagger_server.database.db import db
from swagger_server.database.models.people import FabricGroups, FabricRoles, FabricPeople
from swagger_server.database.models.projects import FabricProjects, ProjectsTags
from swagger_server.models.person import Person
from swagger_server.models.project_membership import ProjectMembership
from swagger_server.models.projects_post import ProjectsPost
from swagger_server.response_code.comanage_utils import create_comanage_role, delete_comanage_role, \
    create_comanage_group
from swagger_server.response_code.preferences_utils import create_projects_preferences
from swagger_server.response_code.profiles_utils import create_profile_projects
from swagger_server.response_code.response_utils import array_difference

logger = logging.getLogger(__name__)


def create_fabric_project_from_api(body: ProjectsPost, project_creator: FabricPeople) -> FabricProjects:
    """
    * Denotes required fields
    - *active
    - co_cou_id_pc
    - co_cou_id_pm
    - co_cou_id_po
    - *description
    - *facility
    - *is_public
    - *name
    - preferences
    - profile
    - project_creators
    - project_members
    - project_owners
    - publications
    - tags
    - *uuid

    {
        "description": "string",
        "is_public": true,
        "name": "string",
        "project_members": [
            "string"
        ],
        "project_owners": [
            "string"
        ]
    }
    """
    # create Project
    fab_project = FabricProjects()
    fab_project.active = False
    fab_project.description = body.description
    fab_project.facility = os.getenv('CORE_API_DEFAULT_FACILITY')
    fab_project.is_public = body.is_public
    fab_project.name = body.name
    fab_project.uuid = uuid4()
    db.session.add(fab_project)
    db.session.commit()
    # create COU groups
    fab_project.co_cou_id_pc = create_comanage_group(
        name=str(fab_project.uuid) + '-pc', description=fab_project.name,
        parent_cou_id=int(os.getenv('COU_ID_PROJECTS')))
    fab_project.co_cou_id_pm = create_comanage_group(
        name=str(fab_project.uuid) + '-pm', description=fab_project.name,
        parent_cou_id=int(os.getenv('COU_ID_PROJECTS')))
    fab_project.co_cou_id_po = create_comanage_group(
        name=str(fab_project.uuid) + '-po', description=fab_project.name,
        parent_cou_id=int(os.getenv('COU_ID_PROJECTS')))
    db.session.commit()
    # create preferences
    create_projects_preferences(fab_project=fab_project)
    # create profile
    create_profile_projects(fab_project=fab_project)
    # add project_creators
    update_projects_personnel(fab_project=fab_project, personnel=[str(project_creator.uuid)], personnel_type='creators')
    # check for project_members
    try:
        if len(body.project_members) == 0:
            print('NO MEMBERS')
    except Exception as exc:
        body.project_members = []
        logger.info("NOP: projects_post(): 'project_members' - {0}".format(exc))
    # add project_members
    update_projects_personnel(fab_project=fab_project, personnel=body.project_members, personnel_type='members')
    # check for project_owners
    try:
        if len(body.project_owners) == 0:
            print('NO OWNERS')
            body.project_owners.append(str(project_creator.uuid))
        else:
            print('SOME OWNERS')
            body.project_owners.append(str(project_creator.uuid))
    except Exception as exc:
        body.project_owners = [str(project_creator.uuid)]
        logger.info("NOP: projects_post(): 'project_owners' - {0}".format(exc))
    # add project_owners
    update_projects_personnel(fab_project=fab_project, personnel=body.project_owners, personnel_type='owners')
    db.session.commit()

    return fab_project


def create_fabric_project_from_uuid(uuid: str) -> FabricProjects:
    """
    * Denotes required fields
    - *active
    - co_cou_id_pc
    - co_cou_id_pm
    - co_cou_id_po
    - *description
    - *facility
    - *is_public
    - *name
    - preferences
    - profile
    - project_creators
    - project_members
    - project_owners
    - publications
    - tags
    - *uuid
    """
    fab_project = FabricProjects.query.filter_by(uuid=uuid).one_or_none()
    if not fab_project:
        fab_project = FabricProjects()
        co_cou_pc = FabricGroups.query.filter_by(name=uuid + '-pc').one_or_none()
        if co_cou_pc:
            # set required fields
            fab_project.active = not co_cou_pc.deleted
            fab_project.created = co_cou_pc.created
            fab_project.description = co_cou_pc.description + ' (autogenerated by script)'
            fab_project.facility = os.getenv('CORE_API_DEFAULT_FACILITY')
            fab_project.is_public = True
            fab_project.name = co_cou_pc.description
            fab_project.uuid = uuid
            db.session.add(fab_project)
            db.session.commit()
            logger.info('CREATE FabricProject: name={0}, uuid={1}'.format(fab_project.name, fab_project.uuid))
            # set optional fields
            fab_project.co_cou_id_pc = co_cou_pc.co_cou_id
            co_cou_pm = FabricGroups.query.filter_by(name=uuid + '-pm').one_or_none()
            if co_cou_pm:
                fab_project.co_cou_id_pm = co_cou_pm.co_cou_id
            co_cou_po = FabricGroups.query.filter_by(name=uuid + '-po').one_or_none()
            if co_cou_po:
                fab_project.co_cou_id_po = co_cou_po.co_cou_id
            # set project preferences
            create_projects_preferences(fab_project=fab_project)
            # set project profile
            create_profile_projects(fab_project=fab_project)
            # set project creators
            for pc_id in [x.people_id for x in FabricRoles.query.filter_by(name=co_cou_pc.name)]:
                pc = FabricPeople.query.filter_by(id=pc_id).one_or_none()
                if pc:
                    fab_project.project_creators.append(pc)
            # set project members
            for pm_id in [x.people_id for x in FabricRoles.query.filter_by(name=co_cou_pm.name)]:
                pm = FabricPeople.query.filter_by(id=pm_id).one_or_none()
                if pm:
                    fab_project.project_members.append(pm)
            # set project owners
            for po_id in [x.people_id for x in FabricRoles.query.filter_by(name=co_cou_po.name)]:
                po = FabricPeople.query.filter_by(id=po_id).one_or_none()
                if po:
                    fab_project.project_owners.append(po)
            db.session.commit()
        else:
            logger.warning(
                "NOT FOUND: create_fabric_project_from_uuid(): Unable to find cou with uuid: '{0}'".format(uuid))

    return fab_project


def get_project_membership(fab_project: FabricProjects, fab_person: FabricPeople) -> ProjectMembership:
    membership = ProjectMembership()
    person_roles = [r.name for r in fab_person.roles]
    membership.is_creator = fab_project.uuid + '-pc' in person_roles
    membership.is_member = fab_project.uuid + '-pm' in person_roles
    membership.is_owner = fab_project.uuid + '-po' in person_roles

    return membership


# Creators, Owners and Members - Projects
def get_projects_personnel(fab_project: FabricProjects = None, personnel_type: str = None) -> [Person]:
    """
    * Denotes required fields
    - email: <string>
    - * name: <string>
    - * uuid: <string>
    """
    personnel = []
    if personnel_type == 'creators':
        personnel = fab_project.project_creators
    elif personnel_type == 'owners':
        personnel = fab_project.project_owners
    elif personnel_type == 'members':
        personnel = fab_project.project_members
    personnel_data = []
    for p in personnel:
        # get preferences (show_email)
        prefs = {pref.key: pref.value for pref in p.preferences}
        # set person attributes
        person = Person()
        person.email = p.preferred_email if prefs.get('show_email') else None
        person.name = p.display_name
        person.uuid = p.uuid
        # add person to personnel_data
        personnel_data.append(person)

    return personnel_data


def update_projects_personnel(fab_project: FabricProjects = None, personnel: [FabricPeople] = None,
                              personnel_type: str = None) -> None:
    personnel = list(set(personnel))
    if personnel_type == 'creators':
        p_orig = [str(p.uuid) for p in fab_project.project_creators]
        p_new = personnel
        p_add = array_difference(p_new, p_orig)
        p_remove = array_difference(p_orig, p_new)
        # get FabricGroup information
        fab_group = FabricGroups.query.filter_by(name=str(fab_project.uuid) + '-pc').one_or_none()
        if fab_group:
            # add project_creators
            for pc in p_add:
                fab_person = FabricPeople.query.filter_by(uuid=pc).one_or_none()
                if fab_person:
                    create_comanage_role(fab_person=fab_person, fab_group=fab_group)
                    fab_project.project_creators.append(fab_person)
                    db.session.commit()
            # remove project_creators
            for pc in p_remove:
                fab_person = FabricPeople.query.filter_by(uuid=pc).one_or_none()
                co_person_role = FabricRoles.query.filter(
                    FabricRoles.co_person_id == fab_person.co_person_id,
                    FabricRoles.co_cou_id == fab_group.co_cou_id,
                    FabricRoles.name == fab_group.name,
                    FabricRoles.people_id == fab_person.id
                ).one_or_none()
                if co_person_role:
                    fab_project.project_creators.remove(fab_person)
                    delete_comanage_role(co_person_role_id=co_person_role.co_person_role_id)
                    db.session.commit()
    elif personnel_type == 'members':
        p_orig = [str(p.uuid) for p in fab_project.project_members]
        p_new = personnel
        p_add = array_difference(p_new, p_orig)
        p_remove = array_difference(p_orig, p_new)
        # get FabricGroup information
        fab_group = FabricGroups.query.filter_by(name=str(fab_project.uuid) + '-pm').one_or_none()
        if fab_group:
            # add project_members
            for pm in p_add:
                fab_person = FabricPeople.query.filter_by(uuid=pm).one_or_none()
                if fab_person:
                    create_comanage_role(fab_person=fab_person, fab_group=fab_group)
                    fab_project.project_members.append(fab_person)
                    db.session.commit()
            # remove project_members
            for pm in p_remove:
                fab_person = FabricPeople.query.filter_by(uuid=pm).one_or_none()
                co_person_role = FabricRoles.query.filter(
                    FabricRoles.co_person_id == fab_person.co_person_id,
                    FabricRoles.co_cou_id == fab_group.co_cou_id,
                    FabricRoles.name == fab_group.name,
                    FabricRoles.people_id == fab_person.id
                ).one_or_none()
                if co_person_role:
                    fab_project.project_members.remove(fab_person)
                    delete_comanage_role(co_person_role_id=co_person_role.co_person_role_id)
                    db.session.commit()
    elif personnel_type == 'owners':
        p_orig = [str(p.uuid) for p in fab_project.project_owners]
        p_new = personnel
        p_add = array_difference(p_new, p_orig)
        p_remove = array_difference(p_orig, p_new)
        # get FabricGroup information
        fab_group = FabricGroups.query.filter_by(name=str(fab_project.uuid) + '-po').one_or_none()
        if fab_group:
            # add project_owners
            for po in p_add:
                fab_person = FabricPeople.query.filter_by(uuid=po).one_or_none()
                if fab_person:
                    create_comanage_role(fab_person=fab_person, fab_group=fab_group)
                    fab_project.project_owners.append(fab_person)
                    db.session.commit()
            # remove project_owners
            for po in p_remove:
                fab_person = FabricPeople.query.filter_by(uuid=po).one_or_none()
                co_person_role = FabricRoles.query.filter(
                    FabricRoles.co_person_id == fab_person.co_person_id,
                    FabricRoles.co_cou_id == fab_group.co_cou_id,
                    FabricRoles.name == fab_group.name,
                    FabricRoles.people_id == fab_person.id
                ).one_or_none()
                if co_person_role:
                    fab_project.project_owners.remove(fab_person)
                    delete_comanage_role(co_person_role_id=co_person_role.co_person_role_id)
                    db.session.commit()
    else:
        logger.error('Invalid personnel_type provided')


def update_projects_tags(fab_project: FabricProjects = None, tags: [str] = None) -> None:
    tags_orig = [p.tag for p in fab_project.tags]
    tags_new = tags
    tags_add = array_difference(tags_new, tags_orig)
    tags_remove = array_difference(tags_orig, tags_new)
    # add projects tags
    for tag in tags_add:
        fab_tag = ProjectsTags.query.filter(
            ProjectsTags.projects_id == fab_project.id, ProjectsTags.tag == tag).one_or_none()
        if not fab_tag:
            fab_tag = ProjectsTags()
            fab_tag.projects_id = fab_project.id
            fab_tag.tag = tag
            fab_project.tags.append(fab_tag)
            db.session.commit()
    # remove projects tags
    for tag in tags_remove:
        fab_tag = ProjectsTags.query.filter(
            ProjectsTags.projects_id == fab_project.id, ProjectsTags.tag == tag).one_or_none()
        if fab_tag:
            fab_project.tags.remove(fab_tag)
            db.session.delete(fab_tag)
            db.session.commit()
