# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ApiOptionsOneApiEndpoints(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, description: str=None, endpoint: str=None):  # noqa: E501
        """ApiOptionsOneApiEndpoints - a model defined in Swagger

        :param description: The description of this ApiOptionsOneApiEndpoints.  # noqa: E501
        :type description: str
        :param endpoint: The endpoint of this ApiOptionsOneApiEndpoints.  # noqa: E501
        :type endpoint: str
        """
        self.swagger_types = {
            'description': str,
            'endpoint': str
        }

        self.attribute_map = {
            'description': 'description',
            'endpoint': 'endpoint'
        }
        self._description = description
        self._endpoint = endpoint

    @classmethod
    def from_dict(cls, dikt) -> 'ApiOptionsOneApiEndpoints':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The api_options_one_api_endpoints of this ApiOptionsOneApiEndpoints.  # noqa: E501
        :rtype: ApiOptionsOneApiEndpoints
        """
        return util.deserialize_model(dikt, cls)

    @property
    def description(self) -> str:
        """Gets the description of this ApiOptionsOneApiEndpoints.


        :return: The description of this ApiOptionsOneApiEndpoints.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ApiOptionsOneApiEndpoints.


        :param description: The description of this ApiOptionsOneApiEndpoints.
        :type description: str
        """

        self._description = description

    @property
    def endpoint(self) -> str:
        """Gets the endpoint of this ApiOptionsOneApiEndpoints.


        :return: The endpoint of this ApiOptionsOneApiEndpoints.
        :rtype: str
        """
        return self._endpoint

    @endpoint.setter
    def endpoint(self, endpoint: str):
        """Sets the endpoint of this ApiOptionsOneApiEndpoints.


        :param endpoint: The endpoint of this ApiOptionsOneApiEndpoints.
        :type endpoint: str
        """

        self._endpoint = endpoint
