# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FacilityUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, button: str=None, content: str=None, _date: date=None, id: int=None, link: str=None, title: str=None, uuid: str=None):  # noqa: E501
        """FacilityUpdate - a model defined in Swagger

        :param button: The button of this FacilityUpdate.  # noqa: E501
        :type button: str
        :param content: The content of this FacilityUpdate.  # noqa: E501
        :type content: str
        :param _date: The _date of this FacilityUpdate.  # noqa: E501
        :type _date: date
        :param id: The id of this FacilityUpdate.  # noqa: E501
        :type id: int
        :param link: The link of this FacilityUpdate.  # noqa: E501
        :type link: str
        :param title: The title of this FacilityUpdate.  # noqa: E501
        :type title: str
        :param uuid: The uuid of this FacilityUpdate.  # noqa: E501
        :type uuid: str
        """
        self.swagger_types = {
            'button': str,
            'content': str,
            '_date': date,
            'id': int,
            'link': str,
            'title': str,
            'uuid': str
        }

        self.attribute_map = {
            'button': 'button',
            'content': 'content',
            '_date': 'date',
            'id': 'id',
            'link': 'link',
            'title': 'title',
            'uuid': 'uuid'
        }
        self._button = button
        self._content = content
        self.__date = _date
        self._id = id
        self._link = link
        self._title = title
        self._uuid = uuid

    @classmethod
    def from_dict(cls, dikt) -> 'FacilityUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The facility_update of this FacilityUpdate.  # noqa: E501
        :rtype: FacilityUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def button(self) -> str:
        """Gets the button of this FacilityUpdate.


        :return: The button of this FacilityUpdate.
        :rtype: str
        """
        return self._button

    @button.setter
    def button(self, button: str):
        """Sets the button of this FacilityUpdate.


        :param button: The button of this FacilityUpdate.
        :type button: str
        """

        self._button = button

    @property
    def content(self) -> str:
        """Gets the content of this FacilityUpdate.


        :return: The content of this FacilityUpdate.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content: str):
        """Sets the content of this FacilityUpdate.


        :param content: The content of this FacilityUpdate.
        :type content: str
        """
        if content is None:
            raise ValueError("Invalid value for `content`, must not be `None`")  # noqa: E501

        self._content = content

    @property
    def _date(self) -> date:
        """Gets the _date of this FacilityUpdate.


        :return: The _date of this FacilityUpdate.
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date: date):
        """Sets the _date of this FacilityUpdate.


        :param _date: The _date of this FacilityUpdate.
        :type _date: date
        """
        if _date is None:
            raise ValueError("Invalid value for `_date`, must not be `None`")  # noqa: E501

        self.__date = _date

    @property
    def id(self) -> int:
        """Gets the id of this FacilityUpdate.


        :return: The id of this FacilityUpdate.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this FacilityUpdate.


        :param id: The id of this FacilityUpdate.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def link(self) -> str:
        """Gets the link of this FacilityUpdate.


        :return: The link of this FacilityUpdate.
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link: str):
        """Sets the link of this FacilityUpdate.


        :param link: The link of this FacilityUpdate.
        :type link: str
        """

        self._link = link

    @property
    def title(self) -> str:
        """Gets the title of this FacilityUpdate.


        :return: The title of this FacilityUpdate.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this FacilityUpdate.


        :param title: The title of this FacilityUpdate.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def uuid(self) -> str:
        """Gets the uuid of this FacilityUpdate.


        :return: The uuid of this FacilityUpdate.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid: str):
        """Sets the uuid of this FacilityUpdate.


        :param uuid: The uuid of this FacilityUpdate.
        :type uuid: str
        """

        self._uuid = uuid
