# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.profile_people import ProfilePeople  # noqa: F401,E501
from swagger_server import util


class PeopleProfilePatch(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, profile: ProfilePeople=None):  # noqa: E501
        """PeopleProfilePatch - a model defined in Swagger

        :param profile: The profile of this PeopleProfilePatch.  # noqa: E501
        :type profile: ProfilePeople
        """
        self.swagger_types = {
            'profile': ProfilePeople
        }

        self.attribute_map = {
            'profile': 'profile'
        }
        self._profile = profile

    @classmethod
    def from_dict(cls, dikt) -> 'PeopleProfilePatch':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The people_profile_patch of this PeopleProfilePatch.  # noqa: E501
        :rtype: PeopleProfilePatch
        """
        return util.deserialize_model(dikt, cls)

    @property
    def profile(self) -> ProfilePeople:
        """Gets the profile of this PeopleProfilePatch.


        :return: The profile of this PeopleProfilePatch.
        :rtype: ProfilePeople
        """
        return self._profile

    @profile.setter
    def profile(self, profile: ProfilePeople):
        """Sets the profile of this PeopleProfilePatch.


        :param profile: The profile of this PeopleProfilePatch.
        :type profile: ProfilePeople
        """

        self._profile = profile
