# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProfilePeopleProfessional(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, url: str=None, type: str=None):  # noqa: E501
        """ProfilePeopleProfessional - a model defined in Swagger

        :param url: The url of this ProfilePeopleProfessional.  # noqa: E501
        :type url: str
        :param type: The type of this ProfilePeopleProfessional.  # noqa: E501
        :type type: str
        """
        self.swagger_types = {
            'url': str,
            'type': str
        }

        self.attribute_map = {
            'url': 'url',
            'type': 'type'
        }
        self._url = url
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'ProfilePeopleProfessional':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The profile_people_professional of this ProfilePeopleProfessional.  # noqa: E501
        :rtype: ProfilePeopleProfessional
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """Gets the url of this ProfilePeopleProfessional.


        :return: The url of this ProfilePeopleProfessional.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this ProfilePeopleProfessional.


        :param url: The url of this ProfilePeopleProfessional.
        :type url: str
        """

        self._url = url

    @property
    def type(self) -> str:
        """Gets the type of this ProfilePeopleProfessional.


        :return: The type of this ProfilePeopleProfessional.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ProfilePeopleProfessional.


        :param type: The type of this ProfilePeopleProfessional.
        :type type: str
        """

        self._type = type
