# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProfileProjectsReferences(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, description: str=None, url: str=None):  # noqa: E501
        """ProfileProjectsReferences - a model defined in Swagger

        :param description: The description of this ProfileProjectsReferences.  # noqa: E501
        :type description: str
        :param url: The url of this ProfileProjectsReferences.  # noqa: E501
        :type url: str
        """
        self.swagger_types = {
            'description': str,
            'url': str
        }

        self.attribute_map = {
            'description': 'description',
            'url': 'url'
        }
        self._description = description
        self._url = url

    @classmethod
    def from_dict(cls, dikt) -> 'ProfileProjectsReferences':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The profile_projects_references of this ProfileProjectsReferences.  # noqa: E501
        :rtype: ProfileProjectsReferences
        """
        return util.deserialize_model(dikt, cls)

    @property
    def description(self) -> str:
        """Gets the description of this ProfileProjectsReferences.


        :return: The description of this ProfileProjectsReferences.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ProfileProjectsReferences.


        :param description: The description of this ProfileProjectsReferences.
        :type description: str
        """

        self._description = description

    @property
    def url(self) -> str:
        """Gets the url of this ProfileProjectsReferences.


        :return: The url of this ProfileProjectsReferences.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this ProfileProjectsReferences.


        :param url: The url of this ProfileProjectsReferences.
        :type url: str
        """

        self._url = url
