# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProjectsCommunitiesPatch(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, communities: List[str]=None):  # noqa: E501
        """ProjectsCommunitiesPatch - a model defined in Swagger

        :param communities: The communities of this ProjectsCommunitiesPatch.  # noqa: E501
        :type communities: List[str]
        """
        self.swagger_types = {
            'communities': List[str]
        }

        self.attribute_map = {
            'communities': 'communities'
        }
        self._communities = communities

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectsCommunitiesPatch':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The projects_communities_patch of this ProjectsCommunitiesPatch.  # noqa: E501
        :rtype: ProjectsCommunitiesPatch
        """
        return util.deserialize_model(dikt, cls)

    @property
    def communities(self) -> List[str]:
        """Gets the communities of this ProjectsCommunitiesPatch.


        :return: The communities of this ProjectsCommunitiesPatch.
        :rtype: List[str]
        """
        return self._communities

    @communities.setter
    def communities(self, communities: List[str]):
        """Sets the communities of this ProjectsCommunitiesPatch.


        :param communities: The communities of this ProjectsCommunitiesPatch.
        :type communities: List[str]
        """

        self._communities = communities
