# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProjectFunding(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, agency: str=None, agency_other: str=None, award_amount: str=None, award_number: str=None, directorate: str=None):  # noqa: E501
        """ProjectFunding - a model defined in Swagger

        :param agency: The agency of this ProjectFunding.  # noqa: E501
        :type agency: str
        :param agency_other: The agency_other of this ProjectFunding.  # noqa: E501
        :type agency_other: str
        :param award_amount: The award_amount of this ProjectFunding.  # noqa: E501
        :type award_amount: str
        :param award_number: The award_number of this ProjectFunding.  # noqa: E501
        :type award_number: str
        :param directorate: The directorate of this ProjectFunding.  # noqa: E501
        :type directorate: str
        """
        self.swagger_types = {
            'agency': str,
            'agency_other': str,
            'award_amount': str,
            'award_number': str,
            'directorate': str
        }

        self.attribute_map = {
            'agency': 'agency',
            'agency_other': 'agency_other',
            'award_amount': 'award_amount',
            'award_number': 'award_number',
            'directorate': 'directorate'
        }
        self._agency = agency
        self._agency_other = agency_other
        self._award_amount = award_amount
        self._award_number = award_number
        self._directorate = directorate

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectFunding':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The project_funding of this ProjectFunding.  # noqa: E501
        :rtype: ProjectFunding
        """
        return util.deserialize_model(dikt, cls)

    @property
    def agency(self) -> str:
        """Gets the agency of this ProjectFunding.


        :return: The agency of this ProjectFunding.
        :rtype: str
        """
        return self._agency

    @agency.setter
    def agency(self, agency: str):
        """Sets the agency of this ProjectFunding.


        :param agency: The agency of this ProjectFunding.
        :type agency: str
        """

        self._agency = agency

    @property
    def agency_other(self) -> str:
        """Gets the agency_other of this ProjectFunding.


        :return: The agency_other of this ProjectFunding.
        :rtype: str
        """
        return self._agency_other

    @agency_other.setter
    def agency_other(self, agency_other: str):
        """Sets the agency_other of this ProjectFunding.


        :param agency_other: The agency_other of this ProjectFunding.
        :type agency_other: str
        """

        self._agency_other = agency_other

    @property
    def award_amount(self) -> str:
        """Gets the award_amount of this ProjectFunding.


        :return: The award_amount of this ProjectFunding.
        :rtype: str
        """
        return self._award_amount

    @award_amount.setter
    def award_amount(self, award_amount: str):
        """Sets the award_amount of this ProjectFunding.


        :param award_amount: The award_amount of this ProjectFunding.
        :type award_amount: str
        """

        self._award_amount = award_amount

    @property
    def award_number(self) -> str:
        """Gets the award_number of this ProjectFunding.


        :return: The award_number of this ProjectFunding.
        :rtype: str
        """
        return self._award_number

    @award_number.setter
    def award_number(self, award_number: str):
        """Sets the award_number of this ProjectFunding.


        :param award_number: The award_number of this ProjectFunding.
        :type award_number: str
        """

        self._award_number = award_number

    @property
    def directorate(self) -> str:
        """Gets the directorate of this ProjectFunding.


        :return: The directorate of this ProjectFunding.
        :rtype: str
        """
        return self._directorate

    @directorate.setter
    def directorate(self, directorate: str):
        """Sets the directorate of this ProjectFunding.


        :param directorate: The directorate of this ProjectFunding.
        :type directorate: str
        """

        self._directorate = directorate
