# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProjectsExpiresOnPatch(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, expires_on: str=None):  # noqa: E501
        """ProjectsExpiresOnPatch - a model defined in Swagger

        :param expires_on: The expires_on of this ProjectsExpiresOnPatch.  # noqa: E501
        :type expires_on: str
        """
        self.swagger_types = {
            'expires_on': str
        }

        self.attribute_map = {
            'expires_on': 'expires_on'
        }
        self._expires_on = expires_on

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectsExpiresOnPatch':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The projects_expires_on_patch of this ProjectsExpiresOnPatch.  # noqa: E501
        :rtype: ProjectsExpiresOnPatch
        """
        return util.deserialize_model(dikt, cls)

    @property
    def expires_on(self) -> str:
        """Gets the expires_on of this ProjectsExpiresOnPatch.


        :return: The expires_on of this ProjectsExpiresOnPatch.
        :rtype: str
        """
        return self._expires_on

    @expires_on.setter
    def expires_on(self, expires_on: str):
        """Sets the expires_on of this ProjectsExpiresOnPatch.


        :param expires_on: The expires_on of this ProjectsExpiresOnPatch.
        :type expires_on: str
        """

        self._expires_on = expires_on
