# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.projects_funding_patch_project_funding import ProjectsFundingPatchProjectFunding  # noqa: F401,E501
from swagger_server import util


class ProjectsFundingPatch(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, project_funding: List[ProjectsFundingPatchProjectFunding]=None):  # noqa: E501
        """ProjectsFundingPatch - a model defined in Swagger

        :param project_funding: The project_funding of this ProjectsFundingPatch.  # noqa: E501
        :type project_funding: List[ProjectsFundingPatchProjectFunding]
        """
        self.swagger_types = {
            'project_funding': List[ProjectsFundingPatchProjectFunding]
        }

        self.attribute_map = {
            'project_funding': 'project_funding'
        }
        self._project_funding = project_funding

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectsFundingPatch':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The projects_funding_patch of this ProjectsFundingPatch.  # noqa: E501
        :rtype: ProjectsFundingPatch
        """
        return util.deserialize_model(dikt, cls)

    @property
    def project_funding(self) -> List[ProjectsFundingPatchProjectFunding]:
        """Gets the project_funding of this ProjectsFundingPatch.


        :return: The project_funding of this ProjectsFundingPatch.
        :rtype: List[ProjectsFundingPatchProjectFunding]
        """
        return self._project_funding

    @project_funding.setter
    def project_funding(self, project_funding: List[ProjectsFundingPatchProjectFunding]):
        """Sets the project_funding of this ProjectsFundingPatch.


        :param project_funding: The project_funding of this ProjectsFundingPatch.
        :type project_funding: List[ProjectsFundingPatchProjectFunding]
        """

        self._project_funding = project_funding
