# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProjectsProjectLeadPatch(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, project_lead: str=None):  # noqa: E501
        """ProjectsProjectLeadPatch - a model defined in Swagger

        :param project_lead: The project_lead of this ProjectsProjectLeadPatch.  # noqa: E501
        :type project_lead: str
        """
        self.swagger_types = {
            'project_lead': str
        }

        self.attribute_map = {
            'project_lead': 'project_lead'
        }
        self._project_lead = project_lead

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectsProjectLeadPatch':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The projects_project_lead_patch of this ProjectsProjectLeadPatch.  # noqa: E501
        :rtype: ProjectsProjectLeadPatch
        """
        return util.deserialize_model(dikt, cls)

    @property
    def project_lead(self) -> str:
        """Gets the project_lead of this ProjectsProjectLeadPatch.


        :return: The project_lead of this ProjectsProjectLeadPatch.
        :rtype: str
        """
        return self._project_lead

    @project_lead.setter
    def project_lead(self, project_lead: str):
        """Sets the project_lead of this ProjectsProjectLeadPatch.


        :param project_lead: The project_lead of this ProjectsProjectLeadPatch.
        :type project_lead: str
        """

        self._project_lead = project_lead
