# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProjectsTagsPatch(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, tags: List[str]=None):  # noqa: E501
        """ProjectsTagsPatch - a model defined in Swagger

        :param tags: The tags of this ProjectsTagsPatch.  # noqa: E501
        :type tags: List[str]
        """
        self.swagger_types = {
            'tags': List[str]
        }

        self.attribute_map = {
            'tags': 'tags'
        }
        self._tags = tags

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectsTagsPatch':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The projects_tags_patch of this ProjectsTagsPatch.  # noqa: E501
        :rtype: ProjectsTagsPatch
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tags(self) -> List[str]:
        """Gets the tags of this ProjectsTagsPatch.


        :return: The tags of this ProjectsTagsPatch.
        :rtype: List[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags: List[str]):
        """Sets the tags of this ProjectsTagsPatch.


        :param tags: The tags of this ProjectsTagsPatch.
        :type tags: List[str]
        """

        self._tags = tags
