# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.quotas_one import QuotasOne  # noqa: F401,E501
from swagger_server.models.status200_ok_paginated import Status200OkPaginated  # noqa: F401,E501
from swagger_server.models.status200_ok_paginated_links import Status200OkPaginatedLinks  # noqa: F401,E501
from swagger_server import util


class Quotas(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, results: List[QuotasOne]=None, limit: int=None, links: Status200OkPaginatedLinks=None, offset: int=None, size: int=None, status: int=200, total: int=None, type: str=None):  # noqa: E501
        """Quotas - a model defined in Swagger

        :param results: The results of this Quotas.  # noqa: E501
        :type results: List[QuotasOne]
        :param limit: The limit of this Quotas.  # noqa: E501
        :type limit: int
        :param links: The links of this Quotas.  # noqa: E501
        :type links: Status200OkPaginatedLinks
        :param offset: The offset of this Quotas.  # noqa: E501
        :type offset: int
        :param size: The size of this Quotas.  # noqa: E501
        :type size: int
        :param status: The status of this Quotas.  # noqa: E501
        :type status: int
        :param total: The total of this Quotas.  # noqa: E501
        :type total: int
        :param type: The type of this Quotas.  # noqa: E501
        :type type: str
        """
        self.swagger_types = {
            'results': List[QuotasOne],
            'limit': int,
            'links': Status200OkPaginatedLinks,
            'offset': int,
            'size': int,
            'status': int,
            'total': int,
            'type': str
        }

        self.attribute_map = {
            'results': 'results',
            'limit': 'limit',
            'links': 'links',
            'offset': 'offset',
            'size': 'size',
            'status': 'status',
            'total': 'total',
            'type': 'type'
        }
        self._results = results
        self._limit = limit
        self._links = links
        self._offset = offset
        self._size = size
        self._status = status
        self._total = total
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'Quotas':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The quotas of this Quotas.  # noqa: E501
        :rtype: Quotas
        """
        return util.deserialize_model(dikt, cls)

    @property
    def results(self) -> List[QuotasOne]:
        """Gets the results of this Quotas.


        :return: The results of this Quotas.
        :rtype: List[QuotasOne]
        """
        return self._results

    @results.setter
    def results(self, results: List[QuotasOne]):
        """Sets the results of this Quotas.


        :param results: The results of this Quotas.
        :type results: List[QuotasOne]
        """

        self._results = results

    @property
    def limit(self) -> int:
        """Gets the limit of this Quotas.


        :return: The limit of this Quotas.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit: int):
        """Sets the limit of this Quotas.


        :param limit: The limit of this Quotas.
        :type limit: int
        """

        self._limit = limit

    @property
    def links(self) -> Status200OkPaginatedLinks:
        """Gets the links of this Quotas.


        :return: The links of this Quotas.
        :rtype: Status200OkPaginatedLinks
        """
        return self._links

    @links.setter
    def links(self, links: Status200OkPaginatedLinks):
        """Sets the links of this Quotas.


        :param links: The links of this Quotas.
        :type links: Status200OkPaginatedLinks
        """

        self._links = links

    @property
    def offset(self) -> int:
        """Gets the offset of this Quotas.


        :return: The offset of this Quotas.
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset: int):
        """Sets the offset of this Quotas.


        :param offset: The offset of this Quotas.
        :type offset: int
        """

        self._offset = offset

    @property
    def size(self) -> int:
        """Gets the size of this Quotas.


        :return: The size of this Quotas.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size: int):
        """Sets the size of this Quotas.


        :param size: The size of this Quotas.
        :type size: int
        """

        self._size = size

    @property
    def status(self) -> int:
        """Gets the status of this Quotas.


        :return: The status of this Quotas.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this Quotas.


        :param status: The status of this Quotas.
        :type status: int
        """

        self._status = status

    @property
    def total(self) -> int:
        """Gets the total of this Quotas.


        :return: The total of this Quotas.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this Quotas.


        :param total: The total of this Quotas.
        :type total: int
        """

        self._total = total

    @property
    def type(self) -> str:
        """Gets the type of this Quotas.


        :return: The type of this Quotas.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Quotas.


        :param type: The type of this Quotas.
        :type type: str
        """

        self._type = type
