# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.quotas_one_resource_type import QuotasOneResourceType  # noqa: F401,E501
from swagger_server import util


class QuotasOne(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, created_at: datetime=None, project_uuid: str=None, quota_limit: float=None, quota_used: float=None, resource_type: QuotasOneResourceType=None, resource_unit: str=None, updated_at: datetime=None, uuid: str=None):  # noqa: E501
        """QuotasOne - a model defined in Swagger

        :param created_at: The created_at of this QuotasOne.  # noqa: E501
        :type created_at: datetime
        :param project_uuid: The project_uuid of this QuotasOne.  # noqa: E501
        :type project_uuid: str
        :param quota_limit: The quota_limit of this QuotasOne.  # noqa: E501
        :type quota_limit: float
        :param quota_used: The quota_used of this QuotasOne.  # noqa: E501
        :type quota_used: float
        :param resource_type: The resource_type of this QuotasOne.  # noqa: E501
        :type resource_type: QuotasOneResourceType
        :param resource_unit: The resource_unit of this QuotasOne.  # noqa: E501
        :type resource_unit: str
        :param updated_at: The updated_at of this QuotasOne.  # noqa: E501
        :type updated_at: datetime
        :param uuid: The uuid of this QuotasOne.  # noqa: E501
        :type uuid: str
        """
        self.swagger_types = {
            'created_at': datetime,
            'project_uuid': str,
            'quota_limit': float,
            'quota_used': float,
            'resource_type': QuotasOneResourceType,
            'resource_unit': str,
            'updated_at': datetime,
            'uuid': str
        }

        self.attribute_map = {
            'created_at': 'created_at',
            'project_uuid': 'project_uuid',
            'quota_limit': 'quota_limit',
            'quota_used': 'quota_used',
            'resource_type': 'resource_type',
            'resource_unit': 'resource_unit',
            'updated_at': 'updated_at',
            'uuid': 'uuid'
        }
        self._created_at = created_at
        self._project_uuid = project_uuid
        self._quota_limit = quota_limit
        self._quota_used = quota_used
        self._resource_type = resource_type
        self._resource_unit = resource_unit
        self._updated_at = updated_at
        self._uuid = uuid

    @classmethod
    def from_dict(cls, dikt) -> 'QuotasOne':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The quotas_one of this QuotasOne.  # noqa: E501
        :rtype: QuotasOne
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this QuotasOne.


        :return: The created_at of this QuotasOne.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this QuotasOne.


        :param created_at: The created_at of this QuotasOne.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def project_uuid(self) -> str:
        """Gets the project_uuid of this QuotasOne.


        :return: The project_uuid of this QuotasOne.
        :rtype: str
        """
        return self._project_uuid

    @project_uuid.setter
    def project_uuid(self, project_uuid: str):
        """Sets the project_uuid of this QuotasOne.


        :param project_uuid: The project_uuid of this QuotasOne.
        :type project_uuid: str
        """

        self._project_uuid = project_uuid

    @property
    def quota_limit(self) -> float:
        """Gets the quota_limit of this QuotasOne.


        :return: The quota_limit of this QuotasOne.
        :rtype: float
        """
        return self._quota_limit

    @quota_limit.setter
    def quota_limit(self, quota_limit: float):
        """Sets the quota_limit of this QuotasOne.


        :param quota_limit: The quota_limit of this QuotasOne.
        :type quota_limit: float
        """

        self._quota_limit = quota_limit

    @property
    def quota_used(self) -> float:
        """Gets the quota_used of this QuotasOne.


        :return: The quota_used of this QuotasOne.
        :rtype: float
        """
        return self._quota_used

    @quota_used.setter
    def quota_used(self, quota_used: float):
        """Sets the quota_used of this QuotasOne.


        :param quota_used: The quota_used of this QuotasOne.
        :type quota_used: float
        """

        self._quota_used = quota_used

    @property
    def resource_type(self) -> QuotasOneResourceType:
        """Gets the resource_type of this QuotasOne.


        :return: The resource_type of this QuotasOne.
        :rtype: QuotasOneResourceType
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type: QuotasOneResourceType):
        """Sets the resource_type of this QuotasOne.


        :param resource_type: The resource_type of this QuotasOne.
        :type resource_type: QuotasOneResourceType
        """

        self._resource_type = resource_type

    @property
    def resource_unit(self) -> str:
        """Gets the resource_unit of this QuotasOne.


        :return: The resource_unit of this QuotasOne.
        :rtype: str
        """
        return self._resource_unit

    @resource_unit.setter
    def resource_unit(self, resource_unit: str):
        """Sets the resource_unit of this QuotasOne.


        :param resource_unit: The resource_unit of this QuotasOne.
        :type resource_unit: str
        """

        self._resource_unit = resource_unit

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this QuotasOne.


        :return: The updated_at of this QuotasOne.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this QuotasOne.


        :param updated_at: The updated_at of this QuotasOne.
        :type updated_at: datetime
        """

        self._updated_at = updated_at

    @property
    def uuid(self) -> str:
        """Gets the uuid of this QuotasOne.


        :return: The uuid of this QuotasOne.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid: str):
        """Sets the uuid of this QuotasOne.


        :param uuid: The uuid of this QuotasOne.
        :type uuid: str
        """

        self._uuid = uuid
