# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
import re  # noqa: F401,E501
from swagger_server import util


class SshkeysPost(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, comment: str=None, description: str=None, keytype: str='sliver', store_pubkey: bool=True):  # noqa: E501
        """SshkeysPost - a model defined in Swagger

        :param comment: The comment of this SshkeysPost.  # noqa: E501
        :type comment: str
        :param description: The description of this SshkeysPost.  # noqa: E501
        :type description: str
        :param keytype: The keytype of this SshkeysPost.  # noqa: E501
        :type keytype: str
        :param store_pubkey: The store_pubkey of this SshkeysPost.  # noqa: E501
        :type store_pubkey: bool
        """
        self.swagger_types = {
            'comment': str,
            'description': str,
            'keytype': str,
            'store_pubkey': bool
        }

        self.attribute_map = {
            'comment': 'comment',
            'description': 'description',
            'keytype': 'keytype',
            'store_pubkey': 'store_pubkey'
        }
        self._comment = comment
        self._description = description
        self._keytype = keytype
        self._store_pubkey = store_pubkey

    @classmethod
    def from_dict(cls, dikt) -> 'SshkeysPost':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The sshkeys_post of this SshkeysPost.  # noqa: E501
        :rtype: SshkeysPost
        """
        return util.deserialize_model(dikt, cls)

    @property
    def comment(self) -> str:
        """Gets the comment of this SshkeysPost.


        :return: The comment of this SshkeysPost.
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment: str):
        """Sets the comment of this SshkeysPost.


        :param comment: The comment of this SshkeysPost.
        :type comment: str
        """
        if comment is None:
            raise ValueError("Invalid value for `comment`, must not be `None`")  # noqa: E501

        self._comment = comment

    @property
    def description(self) -> str:
        """Gets the description of this SshkeysPost.


        :return: The description of this SshkeysPost.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this SshkeysPost.


        :param description: The description of this SshkeysPost.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def keytype(self) -> str:
        """Gets the keytype of this SshkeysPost.


        :return: The keytype of this SshkeysPost.
        :rtype: str
        """
        return self._keytype

    @keytype.setter
    def keytype(self, keytype: str):
        """Sets the keytype of this SshkeysPost.


        :param keytype: The keytype of this SshkeysPost.
        :type keytype: str
        """
        allowed_values = ["bastion", "sliver"]  # noqa: E501
        if keytype not in allowed_values:
            raise ValueError(
                "Invalid value for `keytype` ({0}), must be one of {1}"
                .format(keytype, allowed_values)
            )

        self._keytype = keytype

    @property
    def store_pubkey(self) -> bool:
        """Gets the store_pubkey of this SshkeysPost.


        :return: The store_pubkey of this SshkeysPost.
        :rtype: bool
        """
        return self._store_pubkey

    @store_pubkey.setter
    def store_pubkey(self, store_pubkey: bool):
        """Sets the store_pubkey of this SshkeysPost.


        :param store_pubkey: The store_pubkey of this SshkeysPost.
        :type store_pubkey: bool
        """

        self._store_pubkey = store_pubkey
