# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.status200_ok_no_content_results import Status200OkNoContentResults  # noqa: F401,E501
from swagger_server import util


class Status200OkNoContent(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, results: List[Status200OkNoContentResults]=None, type: str='no_content', size: int=1, status: int=200):  # noqa: E501
        """Status200OkNoContent - a model defined in Swagger

        :param results: The results of this Status200OkNoContent.  # noqa: E501
        :type results: List[Status200OkNoContentResults]
        :param type: The type of this Status200OkNoContent.  # noqa: E501
        :type type: str
        :param size: The size of this Status200OkNoContent.  # noqa: E501
        :type size: int
        :param status: The status of this Status200OkNoContent.  # noqa: E501
        :type status: int
        """
        self.swagger_types = {
            'results': List[Status200OkNoContentResults],
            'type': str,
            'size': int,
            'status': int
        }

        self.attribute_map = {
            'results': 'results',
            'type': 'type',
            'size': 'size',
            'status': 'status'
        }
        self._results = results
        self._type = type
        self._size = size
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Status200OkNoContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The status_200_ok_no_content of this Status200OkNoContent.  # noqa: E501
        :rtype: Status200OkNoContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def results(self) -> List[Status200OkNoContentResults]:
        """Gets the results of this Status200OkNoContent.


        :return: The results of this Status200OkNoContent.
        :rtype: List[Status200OkNoContentResults]
        """
        return self._results

    @results.setter
    def results(self, results: List[Status200OkNoContentResults]):
        """Sets the results of this Status200OkNoContent.


        :param results: The results of this Status200OkNoContent.
        :type results: List[Status200OkNoContentResults]
        """

        self._results = results

    @property
    def type(self) -> str:
        """Gets the type of this Status200OkNoContent.


        :return: The type of this Status200OkNoContent.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Status200OkNoContent.


        :param type: The type of this Status200OkNoContent.
        :type type: str
        """

        self._type = type

    @property
    def size(self) -> int:
        """Gets the size of this Status200OkNoContent.


        :return: The size of this Status200OkNoContent.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size: int):
        """Sets the size of this Status200OkNoContent.


        :param size: The size of this Status200OkNoContent.
        :type size: int
        """

        self._size = size

    @property
    def status(self) -> int:
        """Gets the status of this Status200OkNoContent.


        :return: The status of this Status200OkNoContent.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this Status200OkNoContent.


        :param status: The status of this Status200OkNoContent.
        :type status: int
        """

        self._status = status
